server:
  port: 8080

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
        routes:
          - id: cliente
            uri: http://localhost:9090
            predicates:
              - Path=/api/client/**
          - id: producto
            uri: http://localhost:9091
            predicates:
              - Path=/api/product/**
          - id: game
            uri: http://localhost:9092
            predicates:
              - Path=/api/game/**
          - id: jugadores
            uri: http://localhost:9093
            predicates:
              - Path=/api/jugadores/**
